# Copyright 2018 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

# Add our google/ lib
$LOAD_PATH.unshift ::File.expand_path('../libraries', ::File.dirname(__FILE__))

require 'chef/resource'
require 'google/hash_utils'
require 'google/spanner/network/delete'
require 'google/spanner/network/get'
require 'google/spanner/network/post'
require 'google/spanner/network/put'
require 'google/spanner/property/instanceconfig_name'
require 'google/spanner/property/integer'
require 'google/spanner/property/namevalues'
require 'google/spanner/property/string'

module Google
  module GSPANNER
    # A provider to manage Google Spanner resources.
    class Instance < Chef::Resource
      resource_name :gspanner_instance

      property :i_label,
               String,
               coerce: ::Google::Spanner::Property::String.coerce,
               name_property: true, desired_state: true
      property :config,
               [String, ::Google::Spanner::Data::InstanceConfigNameRef],
               coerce: ::Google::Spanner::Property::InstanceConfigNameRef.coerce,
               desired_state: true
      property :display_name,
               String, coerce: ::Google::Spanner::Property::String.coerce, desired_state: true
      property :node_count,
               Integer, coerce: ::Google::Spanner::Property::Integer.coerce, desired_state: true
      property :labels,
               [Hash, ::Google::Spanner::Property::NameValues],
               coerce: ::Google::Spanner::Property::NameValues.coerce, desired_state: true

      property :credential, String, desired_state: false, required: true
      property :project, String, desired_state: false, required: true

      action :create do
        fetch = fetch_resource(@new_resource, self_link(@new_resource))
        if fetch.nil?
          converge_by "Creating gspanner_instance[#{new_resource.name}]" do
            # TODO(nelsonjr): Show a list of variables to create
            # TODO(nelsonjr): Determine how to print green like update converge
            puts # making a newline until we find a better way TODO: find!
            compute_changes.each { |log| puts "    - #{log.strip}\n" }
            create_req = ::Google::Spanner::Network::Post.new(
              collection(@new_resource), fetch_auth(@new_resource),
              'application/json', resource_to_create
            )
            return_if_object create_req.send
          end
        else
          @current_resource = @new_resource.clone
          @current_resource.i_label = ::Google::Spanner::Property::String.api_parse(fetch['name'])
          @current_resource.config =
            ::Google::Spanner::Property::InstanceConfigNameRef.api_parse(fetch['config'])
          @current_resource.display_name =
            ::Google::Spanner::Property::String.api_parse(fetch['displayName'])
          @current_resource.node_count =
            ::Google::Spanner::Property::Integer.api_parse(fetch['nodeCount'])
          @current_resource.labels =
            ::Google::Spanner::Property::NameValues.api_parse(fetch['labels'])

          update
        end
      end

      action :delete do
        fetch = fetch_resource(@new_resource, self_link(@new_resource))
        unless fetch.nil?
          converge_by "Deleting gspanner_instance[#{new_resource.name}]" do
            delete_req = ::Google::Spanner::Network::Delete.new(
              self_link(@new_resource), fetch_auth(@new_resource)
            )
            return_if_object delete_req.send
          end
        end
      end

      # TODO(nelsonjr): Add actions :manage and :modify

      def exports
        {
          name: i_label
        }
      end

      private

      action_class do
        def resource_to_request
          request = {
            name: new_resource.i_label,
            config: new_resource.config,
            displayName: new_resource.display_name,
            nodeCount: new_resource.node_count,
            labels: new_resource.labels
          }.reject { |_, v| v.nil? }
          request.to_json
        end

        def update
          converge_if_changed do |_vars|
            # TODO(nelsonjr): Determine how to print indented like upd converge
            # TODO(nelsonjr): Check w/ Chef... can we print this in red?
            puts # making a newline until we find a better way TODO: find!
            compute_changes.each { |log| puts "    - #{log.strip}\n" }
            update_req =
              ::Google::Spanner::Network::Patch.new(self_link(@new_resource),
                                                    fetch_auth(@new_resource),
                                                    'application/json',
                                                    resource_to_update)
            return_if_object update_req.send, ''
          end
        end

        def self.fetch_export(resource, type, id, property)
          return if id.nil?
          resource.resources("#{type}[#{id}]").exports[property]
        end

        def self.resource_to_hash(resource)
          {
            project: resource.project,
            name: resource.i_label,
            config: resource.config,
            display_name: resource.display_name,
            node_count: resource.node_count,
            labels: resource.labels
          }.reject { |_, v| v.nil? }
        end

        # Copied from Chef > Provider > #converge_if_changed
        def compute_changes
          properties = @new_resource.class.state_properties.map(&:name)
          properties = properties.map(&:to_sym)
          if current_resource
            compute_changes_for_existing_resource properties
          else
            compute_changes_for_new_resource properties
          end
        end

        # Collect the list of modified properties
        def compute_changes_for_existing_resource(properties)
          specified_properties = properties.select do |property|
            @new_resource.property_is_set?(property)
          end
          modified = specified_properties.reject do |p|
            @new_resource.send(p) == current_resource.send(p)
          end

          generate_pretty_green_text(modified)
        end

        def generate_pretty_green_text(modified)
          property_size = modified.map(&:size).max
          modified.map! do |p|
            properties_str = if @new_resource.sensitive
                               '(suppressed sensitive property)'
                             else
                               [
                                 @new_resource.send(p).inspect,
                                 "(was #{current_resource.send(p).inspect})"
                               ].join(' ')
                             end
            "  set #{p.to_s.ljust(property_size)} to #{properties_str}"
          end
        end

        # Write down any properties we are setting.
        def compute_changes_for_new_resource(properties)
          property_size = properties.map(&:size).max
          properties.map do |property|
            default = ' (default value)' \
              unless @new_resource.property_is_set?(property)
            next if @new_resource.send(property).nil?
            properties_str = if @new_resource.sensitive
                               '(suppressed sensitive property)'
                             else
                               @new_resource.send(property).inspect
                             end
            ["  set #{property.to_s.ljust(property_size)}",
             "to #{properties_str}#{default}"].join(' ')
          end.compact
        end

        def fetch_auth(resource)
          self.class.fetch_auth(resource)
        end

        def self.fetch_auth(resource)
          resource.resources("gauth_credential[#{resource.credential}]")
                  .authorization
        end

        def fetch_resource(resource, self_link)
          self.class.fetch_resource(resource, self_link)
        end

        def debug(message)
          Chef::Log.debug(message)
        end

        def self.collection(data)
          URI.join(
            'https://spanner.googleapis.com/v1/',
            expand_variables(
              'projects/{{project}}/instances',
              data
            ).split('/').map { |p| p.gsub('%3A', ':') }
                        .join('/')
          )
        end

        def collection(data)
          self.class.collection(data)
        end

        def self.self_link(data)
          URI.join(
            'https://spanner.googleapis.com/v1/',
            expand_variables(
              'projects/{{project}}/instances/{{name}}',
              data
            ).split('/').map { |p| p.gsub('%3A', ':') }
                        .join('/')
          )
        end

        def self_link(data)
          self.class.self_link(data)
        end

        def self.return_if_object(response, allow_not_found = false)
          raise "Bad response: #{response.body}" \
            if response.is_a?(Net::HTTPBadRequest)
          raise "Bad response: #{response}" \
            unless response.is_a?(Net::HTTPResponse)
          return if response.is_a?(Net::HTTPNotFound) && allow_not_found 
          return if response.is_a?(Net::HTTPNoContent)
          result = decode_response(response)
          raise_if_errors result, %w[error errors], 'message'
          raise "Bad response: #{response}" unless response.is_a?(Net::HTTPOK)
          result
        end

        def return_if_object(response, allow_not_found = false)
          self.class.return_if_object(response, allow_not_found)
        end

        def self.extract_variables(template)
          template.scan(/{{[^}]*}}/).map { |v| v.gsub(/{{([^}]*)}}/, '\1') }
                  .map(&:to_sym)
        end

        def self.expand_variables(template, var_data, extra_data = {})
          data = if var_data.class <= Hash
                   var_data.merge(extra_data)
                 else
                   resource_to_hash(var_data).merge(extra_data)
                 end
          extract_variables(template).each do |v|
            unless data.key?(v)
              raise "Missing variable :#{v} in #{data} on #{caller.join("\n")}}"
            end
            template.gsub!(/{{#{v}}}/, CGI.escape(data[v].to_s))
          end
          template
        end

        def decode_response(response)
          self.class.decode_response(response)
        end

        def self.decode_response(response)
          response = JSON.parse(response.body)
          return response if response.empty?
          # Don't alter if it's a async operation
          return response if response['name'].include? '/operations/'

          response['name'] = response['name'].split('/').last
          response['config'] = response['config'].split('/').last
          response
        end

        def resource_to_create
          instance = JSON.parse(resource_to_request)
          instance['name'] =
            "projects/#{@new_resource.project}/instances/#{@new_resource.i_label}"
          instance['config'] =
            "projects/#{@new_resource.project}/instanceConfigs/#{@new_resource.config}"
          {
            'instanceId' => @new_resource.i_label,
            'instance' => instance
          }.to_json
        end

        def resource_to_update
          instance = JSON.parse(resource_to_request)
          instance['name'] =
            "projects/#{@new_resource.project}/instances/#{@new_resource.i_label}"
          instance['config'] =
            "projects/#{@new_resource.project}/instanceConfigs/#{@new_resource.config}"
          {
            'instance' => instance,
            'fieldMask' => %w[name config displayName nodeCount labels].join(',')
          }.to_json
        end

        def self.fetch_resource(resource, self_link)
          get_request = ::Google::Spanner::Network::Get.new(
            self_link, fetch_auth(resource)
          )
          return_if_object get_request.send, true
        end

        def self.raise_if_errors(response, err_path, msg_field)
          errors = ::Google::HashUtils.navigate(response, err_path)
          raise_error(errors, msg_field) unless errors.nil?
        end

        def self.raise_error(errors, msg_field)
          raise IOError, ['Operation failed:',
                          errors.map { |e| e[msg_field] }.join(', ')].join(' ')
        end
      end
    end
  end
end
